[tool.isort]
combine_as_imports = true
known_first_party = ["yax"]
multi_line_output = 4

[tool.mypy]
no_implicit_optional = true

show_column_numbers = true
show_error_codes = true
show_error_context = false

warn_unused_ignores = true

plugins = ["numpy.typing.mypy_plugin"]

[tool.pytest.ini_options]
minversion = "8.2"
addopts = "-ra -q -m 'not slow' --no-header"
testpaths = ["tests"]
markers = [
    "slow: slow tests (deselect with '-m \"not slow\"')",
    "cuda: tests that requires CUDA",
]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
indent-width = 4
line-length = 79
extend-exclude = []

[tool.ruff.lint]
select = ["E", "F", "NPY", "PYI", "PTH"]
ignore = ["PTH123"]
preview = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.pycodestyle]
max-doc-length = 79
max-line-length = 79

[tool.yapf]
based_on_style = "pep8"
